name: Comment on New Issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add guidelines comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "👋 Thanks for opening this issue! We'll look into it as soon as possible, estimated time for response is **18–24 hrs**.\nIf your issue goes stale beyond this timeframe, kindly contact mentors or PAs via our [Discord server](https://discord.gg/thMjv3HtP2).\n### ⏱️ Issue response & contact\n- In the meantime, provide screenshots, videos, or other context to speed review and assignment.\n- If relevant, **please mention whether this issue is raised under _GGSoC_ or _OSCI_** when you create the issue.\n- If you have questions, comment below or ping any mentor on [discord](https://discord.gg/thMjv3HtP2).\n---\n### 📝 Guidelines for Raising Issues\nTo ensure quality moving forward:\n\n**For UI/UX contributions**\n\n- You **must include a design** (Figma link, image, or wireframe) when raising an issue **(if applicable)**.\n- Issues without visual references will **not be accepted**.\n- If the change is a modification, share screenshots of the area you want to change.\n\n**For Backend contributions**\n\n- You **must share a brief execution plan** what you intend to build, how it works, and why it's needed.\n- Vague issues will be closed without review.\n---\n### 📝 Guidelines for Opening Pull Requests\n- **Your PRs should target the \`master\` branch.**\n- **No one is allowed to push directly to \`main\`.**\n- **All PRs which do not mention an issue will be closed without review.**\n- **Do NOT raise a PR unless the issue is assigned to you.**\n---\n### ✅ Quick checklist (please attach before requesting assignment)\n- [ ] Design link or screenshot (for UI/UX)  \n- [ ] Execution plan (for backend)  \n- [ ] Mention if this is under **GGSoC** / **OSCI**  \n- [ ] Any related issue/PR numbers referenced\n---\nHappy contributing 🚀\n<!-- notesvault-guidelines -->"
              })
